services:
  app:
    image: bdf
    build:
      context: ./bloglist-front/
      dockerfile: dev.Dockerfile
    volumes:
      - ./bloglist-front/:/usr/src/app
    ports:
      - 3000:3000
    #environment:
    #  - WATCHPACK_POLLING=true
    container_name: bloglist-front-dev
  server:
    image: bbd
    container_name: bloglist-back-dev
    build:
      context: ./bloglist-back/
      dockerfile: dev.Dockerfile
      args:
        - DOCKER_ENV = TRUE
    volumes:
      - ./bloglist-back/:/usr/src/app
    ports:
      - 3003:3003
    environment:
      - DOCKER_ENV = TRUE
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy-3
    depends_on:
      - app # wait for the frontend container to be started
