# fly.toml app configuration file generated for morning-butterfly-9483 on 2023-08-03T12:55:25+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "morning-butterfly-9483"
primary_region = "arn"

[experimental]
  auto_rollback = true

[build]

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080 #3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services]]
  protocol = ""
  internal_port = 8080
  processes = ["app"]
  #kokeilut alkaa - 
  #protocol = "tcp"

#[[services.ports]]
    #force_https = true
   # handlers = ["http"]
    #port = 3000
