name: Testing+etc pipeline

on:
  push:
    branches:
      - master

jobs:
  simple_deployment_pipeline:
    if: ${{ !contains( github.event.head_commit.message, '#skip-deplo') }}
    runs-on: ubuntu-20.04
    env:
      MONGODB_URI: ${{secrets.MONGODB_URI}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install dependencies back
        working-directory: ./bloglist-back
        run: npm install
      - name: Install dependencies front
        working-directory: ./bloglist-front
        run: npm install
      - name: Check style back
        working-directory: ./bloglist-back
        run: npm run eslint .
      - name: Check style front
        working-directory: ./bloglist-front
        run: npm run eslint
      - name: Tests
        working-directory: ./bloglist-back
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy app
        if: ${{ github.event_name == 'push' && !contains( github.event.head_commit.message, '#skip') }}
        working-directory: ./bloglist-back
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
